Added option for retirement rarity
Egoistically/ALAuto pull request #89
Opened 2020-02-20 16:38 UTC by wiseasswolfofyoitsu

* Broke out Retirement module into its own section in the config
* Added the ability to turn off retiring rares.

2020-02-20 19:50 UTC, Egoistically commented
Can you also add an option to disable commons? Doing so makes no sense but just to have the option available for any possible psychopaths.

2020-02-20 20:41 UTC, wiseasswolfofyoitsu commented
Would be a pretty trivial mod, yeah.

2020-02-20 21:37 UTC, wiseasswolfofyoitsu commented
Ok, option for commons retiring added, along with some config safety checks, for all the pedants out there!

2020-02-20 21:43 UTC, Egoistically requested changes

2020-02-20 21:43 UTC, Egoistically commented on util/config.py
> +            sys.exit(1)
This should go inside `validate` function (around line 199), and instead of using `sys.exit(1)` you should use `self.ok = False`.

2020-02-21 02:53 UTC, wiseasswolfofyoitsu commented
Change request should be resolved

2020-02-21 03:17 UTC, Egoistically approved these changes

2020-02-21 03:18 UTC, Egoistically commented
I have another question, doesn't this `if not (self.retirement['commons'] or self.retirement['rares'])` mean that if either of both is disabled it won't work?

2020-02-21 03:25 UTC, wiseasswolfofyoitsu commented
It only goes into the error handler if both are disabled and passes if either or both are enabled. It's logically equivalent to `if Not Commons and Not Rares`

2020-02-21 03:37 UTC, Egoistically commented
Aight, looks good to me.

2020-02-21 03:37 UTC, merged